[package]
name = "minesweeper"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "^0.32.1"
image = "^0.24.2"
ndarray = "^0.15.4"
rand = "^0.8.5"